apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
  labels:
    app: {{ .Values.pod.name }}
spec:
  containers:
    - name: {{ .Values.pod.name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      ports:
        - containerPort: {{ .Values.containerPort }}

