name: Spring Boot Maven CI with Wrapper

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Grant mvnw permission
      run: chmod +x ./mvnw

    - name: Build with Maven Wrapper
      run: ./mvnw clean package -DskipTests

    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: springboot-jar
        path: target/*.jar